// Curated blocklist of disposable / throwaway email domains. Used by the
// sign-up flow to refuse account creation with addresses that exist for a
// few minutes and then disappear. The list is intentionally a small,
// well-known core (mailinator, guerrilla, yopmail, 10-minute, temp-mail,
// dropmail, etc.) plus the most-used aliases each service exposes. It
// won't catch every domain in the wild but it filters out the bulk of
// drive-by signups without needing a network call.
//
// Match is on the part after the last "@", lowercased and trimmed. Anything
// not in this set passes through.

const Set<String> DISPOSABLE_EMAIL_DOMAINS = {
  // Mailinator family
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'letthemeatspam.com',
  'mailinater.com',
  'mailinator.us',
  'notmailinator.com',
  'reallymymail.com',
  'reconmail.com',
  'safetymail.info',
  'sendspamhere.com',
  'sogetthis.com',
  'spambooger.com',
  'streetwisemail.com',
  'suremail.info',
  'thisisnotmyrealemail.com',
  'tradermail.info',
  'veryrealemail.com',
  'zippymail.info',

  // 10 Minute Mail family
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemail.de',
  '20minutemail.com',
  '20minutemail.it',
  '30minutemail.com',
  '5mail.cf',
  '60minutemail.com',

  // Temp Mail family
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.com',
  'temp-mail.ru',
  'tempmail.com',
  'tempmail.net',
  'tempmail.email',
  'tempmail.dev',
  'tempmail.us',
  'tempmail.plus',
  'tempmail.de',
  'tempmailaddress.com',
  'tempmailo.com',
  'tempinbox.com',
  'tempinbox.co.uk',
  'tempemail.co',
  'tempemail.com',
  'tempemail.net',
  'temporarymail.com',

  // Guerrilla Mail family
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'guerrillamail.de',
  'guerrillamailblock.com',
  'sharklasers.com',
  'grr.la',
  'pokemail.net',
  'spam4.me',

  // YopMail family
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',

  // 1secmail family
  '1secmail.com',
  '1secmail.net',
  '1secmail.org',
  'wwjmp.com',
  'esiix.com',
  'xojxe.com',

  // DropMail family
  'dropmail.me',
  'emltmp.com',
  '10mail.org',
  '31mail.com',
  'flymail.tk',
  'zetmail.com',

  // Other widely-used disposable services
  'maildrop.cc',
  'getnada.com',
  'nada.email',
  'inboxbear.com',
  'inboxkitten.com',
  'dispostable.com',
  'fakeinbox.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'emailfake.com',
  'fakemailgenerator.net',
  'throwawaymail.com',
  'throwam.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.de',
  'trash-mail.com',
  'trash-mail.de',
  'trbvm.com',
  'mohmal.com',
  'emailondeck.com',
  'mintemail.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spambox.us',
  'spambog.com',
  'spambog.de',
  'mailcatch.com',
  'mailnesia.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'mytemp.email',
  'mytrashmail.com',
  'moakt.com',
  'boximail.com',
  'disbox.net',
  'disbox.org',
  'mvrht.com',
  'mailimate.com',
  'ezztt.com',
  'jetable.org',
  '33mail.com',
  '0815.ru',
  'byom.de',
  'airmail.cc',
  'gufum.com',
  'mailsac.com',
  'easytrashmail.com',
  'minutemail.cf',
  'smwg.info',
  'tmail.ws',
  'tmpmail.org',
  'tmpmail.net',
  'mail-temp.com',
  'mail-temporaire.fr',
  'mail-temporaire.com',
  'instant-mail.de',
  'mailtemp.info',
  'getairmail.com',
  'inboxalias.com',
  'mvrht.net',
  'spambox.org',
  'tafmail.com',
  'tmail.com',
  'tmail.io',
  'tempr.email',
  'youmailr.com',
  'youremail.cf',
  'mt2014.com',
  'mt2015.com',
  'thankyou2010.com',
  'odaymail.com',
  'mail.ru.spam',
  'rcpt.at',
  'kasmail.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.info',
  'wegwerfemail.de',
  'wegwerfemail.com',
  'wegwerfemail.net',
  'wegwerfemail.info',
  'spam.la',
  'sneakemail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sofortmail.de',
  'soodonims.com',
  'bccto.me',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
};

// Returns true when the address's domain is in the disposable blocklist.
// Lowercases + trims so casing or accidental whitespace doesn't slip
// through. Malformed addresses (no "@", no domain segment) return false
// so the regular email-format validation can flag them with its own
// message instead of getting hijacked by this check.
bool isDisposableEmail(String email) {
  final String trimmed = email.trim().toLowerCase();
  final int atIndex = trimmed.lastIndexOf('@');
  final bool hasNoAtSign = atIndex <= 0 || atIndex == trimmed.length - 1;

  if (hasNoAtSign) {
    return false;
  }

  final String domain = trimmed.substring(atIndex + 1);

  return DISPOSABLE_EMAIL_DOMAINS.contains(domain);
}
