// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKL7UCkGiWASDXBs080RjcVt8pPQfc5k',
    appId: '1:976267746377:web:8bd98125ac35c3cd507398',
    messagingSenderId: '976267746377',
    projectId: 'readlock-production',
    authDomain: 'readlock-production.firebaseapp.com',
    storageBucket: 'readlock-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGhRV482BHQ2NiKT2t8WY0mjk8N53zno',
    appId: '1:976267746377:android:f685520649f9c5b1507398',
    messagingSenderId: '976267746377',
    projectId: 'readlock-production',
    storageBucket: 'readlock-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5khSAhPBcJxGzpHz8etLgAhGWms2Tmc',
    appId: '1:976267746377:ios:30b619f11b8ac41c507398',
    messagingSenderId: '976267746377',
    projectId: 'readlock-production',
    storageBucket: 'readlock-production.firebasestorage.app',
    iosClientId: '976267746377-ml00p50nngsr9hg8fb65jl6o7rpmdgq8.apps.googleusercontent.com',
    iosBundleId: 'org.readlock.readlock',
  );

}